spring:
  rabbitmq:
    host: 192.168.101.65
    port: 5672
    username: guest
    password: guest
    virtual-host: /         #虚拟机
      #cache:
      #connection:
    #mode: channel  #一个连接可以带多个通道

    #-----------------------消费端配置------------------------------------
    #签收模式配置
    listener:
      simple:
        acknowledge-mode: manual    #手动签收,接收后要channel.ba
        prefetch: 1      #每次只能获取1条消息，处理完成才能获取下一个消息
        retry:
          enabled: true  #开启消费者失败重试
          initial-interval: 1000  #第一次失败重试为1秒
          multiplier: 1  #下次失败的等待时长倍数，下次等待时长 = multiplier * 上次的时长
          max-attempts: 3  #最大重试次数
          max-interval: 10000  #最大等待时长10秒
          stateless: true  #true无状态，false有状态。如果业务中包含事务，这里改为false
